### ISSUE TITLE
AttributeError: 'RegexURLPattern' object has no attribute 'app_name'

### ISSUE THREAD

**Issue by ChillarAnand** [zniper/django-quickadmin#1]
when i try to run server it is throwing this error.
i am using `Django==1.7.5`

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/k3/.virtualenvs/exp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/k3/.virtualenvs/exp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/k3/.virtualenvs/exp/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/k3/.virtualenvs/exp/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/k3/.virtualenvs/exp/local/lib/python2.7/site-packages/quickadmin/apps.py", line 10, in ready
    register_models()
  File "/home/k3/.virtualenvs/exp/local/lib/python2.7/site-packages/quickadmin/register.py", line 73, in register_models
    update_admin_urls()
  File "/home/k3/.virtualenvs/exp/local/lib/python2.7/site-packages/quickadmin/register.py", line 48, in update_admin_urls
    if url_item.app_name == 'admin':
AttributeError: 'RegexURLPattern' object has no attribute 'app_name'
```

**Comment by zniper** [comment]
Could you post the URL configuration for admin in the root `urlpatterns`? I supposed that's currently using callback function.

**Comment by ChillarAnand** [comment]
here it is 

```
admin.autodiscover()

urlpatterns = patterns(
    '',

    url(r'^500/$', 'django.views.defaults.server_error'),
    url(r'^home/', include('apps.home.urls', namespace='home')),
    url(r'^project/', (include('apps.project.urls', namespace='project'))),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', HomeView.as_view()),
) + static(MEDIA_URL, document_root=MEDIA_ROOT)
```

**Comment by zniper** [comment]
Thank you @ChillarAnand for the issue report.

**Comment by ChillarAnand** [comment]
thanks for quick response. its working now.

when i start server it is showing this message 

```
No handlers could be found for logger "quickadmin.register"
```
